namespace Dbos.Transact.Conductor.Protocol;

public enum MessageType
{
    Alert,
    BackfillSchedule,
    Cancel,
    Delete,
    ExecutorInfo,
    ExistPendingWorkflows,
    ExportWorkflow,
    ForkWorkflow,
    GetMetrics,
    GetSchedule,
    GetWorkflowAggregates,
    GetWorkflowEvents,
    GetWorkflowNotifications,
    GetWorkflowStreams,
    GetWorkflow,
    ImportWorkflow,
    ListApplicationVersions,
    ListQueuedWorkflows,
    ListSchedules,
    ListSteps,
    ListWorkflows,
    PauseSchedule,
    Recovery,
    Restart,
    Resume,
    ResumeSchedule,
    Retention,
    SetLatestApplicationVersion,
    TriggerSchedule,
}

internal static class MessageTypeExtensions
{
    public static string GetValue(this MessageType type) => type switch
    {
        MessageType.Alert => "alert",
        MessageType.BackfillSchedule => "backfill_schedule",
        MessageType.Cancel => "cancel",
        MessageType.Delete => "delete",
        MessageType.ExecutorInfo => "executor_info",
        MessageType.ExistPendingWorkflows => "exist_pending_workflows",
        MessageType.ExportWorkflow => "export_workflow",
        MessageType.ForkWorkflow => "fork_workflow",
        MessageType.GetMetrics => "get_metrics",
        MessageType.GetSchedule => "get_schedule",
        MessageType.GetWorkflowAggregates => "get_workflow_aggregates",
        MessageType.GetWorkflowEvents => "get_workflow_events",
        MessageType.GetWorkflowNotifications => "get_workflow_notifications",
        MessageType.GetWorkflowStreams => "get_workflow_streams",
        MessageType.GetWorkflow => "get_workflow",
        MessageType.ImportWorkflow => "import_workflow",
        MessageType.ListApplicationVersions => "list_application_versions",
        MessageType.ListQueuedWorkflows => "list_queued_workflows",
        MessageType.ListSchedules => "list_schedules",
        MessageType.ListSteps => "list_steps",
        MessageType.ListWorkflows => "list_workflows",
        MessageType.PauseSchedule => "pause_schedule",
        MessageType.Recovery => "recovery",
        MessageType.Restart => "restart",
        MessageType.Resume => "resume",
        MessageType.ResumeSchedule => "resume_schedule",
        MessageType.Retention => "retention",
        MessageType.SetLatestApplicationVersion => "set_latest_application_version",
        MessageType.TriggerSchedule => "trigger_schedule",
        _ => throw new ArgumentOutOfRangeException(nameof(type), type, null),
    };
}
