<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!-- Test infrastructure -->
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.4.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="9.0.4" />
    <PackageVersion Include="Npgsql" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
  </ItemGroup>

</Project>
