<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Dbos.Transact.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations/Sql/Postgres/*.sql" />
    <EmbeddedResource Include="Migrations/Sql/Sqlite/*.sql" />
  </ItemGroup>

</Project>
